
/* SIMPLE EXMAPLE: CREATE TABLE AND FOREIGN KEY REFERENCE TO CUSTOMERS TABLE */

USE usersdb
CREATE TABLE Orders 
(
	Id INT PRIMARY KEY IDENTITY,
	CustomerId INT, 
	CreateAt Date,
	CONSTRAINT FK_Orders_To_Customers FOREIGN KEY (CustomerId) REFERENCES Customers (Id)
);